{% set name = "python-ace" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ICAMS/python-ace/archive/75300ebba0fad65553e8ccb9c75b15ea090d0700.tar.gz
  sha256: ba05ba784e3020e45b67896cdf4e6e960a41346487349233b1318cc9f99f6f64
  patches:
    - setup.patch  # [osx]
    - pybind.patch
    - yaml.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pybind11
  run:
    - python
    - ase
    - numpy
    - pandas
    - psutil
    - ruamel.yaml
    - libcxx  # [osx]

test:
  imports:
    - pyace
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ICAMS/python-ace/
  summary: 'pacemaker - a tool for fitting of interatomic potentials in a general nonlinear Atomic Cluster Expansion (ACE) form'
  description: |
    pacemaker - a tool for fitting of interatomic potentials in a general
    nonlinear Atomic Cluster Expansion (ACE) form.
  license: ASL
  license_family: OTHER
  license_file: LICENSE.md
  doc_url: https://pacemaker.readthedocs.io
  dev_url: https://github.com/ICAMS/python-ace/

extra:
  recipe-maintainers:
    - srmnitc
    - jan-janssen
