{% set name = "python-ace" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ICAMS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 548c14a463943e1dcc62143ef904370e15e5928ea9ad0c9d236d607020a1f38a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - ase
    - numpy
    - pandas
    - psutil
    - ruamel.yaml

test:
  imports:
    - pyace
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ICAMS/python-ace/
  summary: 'pacemaker - a tool for fitting of interatomic potentials in a general nonlinear Atomic Cluster Expansion (ACE) form'
  description: |
    pacemaker - a tool for fitting of interatomic potentials in a general
    nonlinear Atomic Cluster Expansion (ACE) form.
  license: ASL
  license_family: OTHER
  license_file: LICENSE.md
  doc_url: https://pacemaker.readthedocs.io
  dev_url: https://github.com/ICAMS/python-ace/

extra:
  recipe-maintainers:
    - jan-janssen
